version: '3.1'
services:
  app:
    container_name: birds
    image: birds
    build: ./
    ports:
      - "8081:5000"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=birdsappdb
      - PGDATA = /var/lib/postgresql/data/pgdata