spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/birdsappdb
    username: postgres
    password: postgres
  liquibase:
    changelog: classpath:db/changelog/changelog-master.xml

server:
  port: 5000